management:
  context_path: /admin
#security:
#  user:
#    password: password

debug: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.kerz: DEBUG
    org.springframework.boot.autoconfigure.security: INFO
    com.orienttechnologies: DEBUG
    
server:
  port: 8081

#---
#spring:
#  profiles: dev
orient:
  host: 192.168.99.100
  user: root
  password: s3cret
  db: tk-test-1

