management:
  context_path: /admin
#security:
#  user:
#    password: password

debug: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.kerz: DEBUG
    org.springframework.boot.autoconfigure.security: INFO
    
server:
  port: 8081
